/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package net.iyouyu.schedule;

public final class R {
    public static final class array {
        /**  系统设置界面需要要到的数组 
         */
        public static final int auto_update_frequency_entry=0x7f050000;
        public static final int auto_update_frequency_value=0x7f050001;
        /**  课节设置界面需要要到的数组 
         */
        public static final int bg_entry=0x7f050002;
        public static final int bg_value=0x7f050003;
        /**  课节设置界面需要要到的数组 
         */
        public static final int classno_entry=0x7f050004;
        public static final int classno_value=0x7f050005;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int a11_12=0x7f020000;
        public static final int a1_2=0x7f020001;
        public static final int a3_4=0x7f020002;
        public static final int a5_6=0x7f020003;
        public static final int a7_8=0x7f020004;
        public static final int a9_10=0x7f020005;
        public static final int alarm=0x7f020006;
        public static final int bg2=0x7f020007;
        public static final int bg3=0x7f020008;
        public static final int bg4=0x7f020009;
        public static final int bg_cal_card9=0x7f02000a;
        public static final int bg_hdpi=0x7f02000b;
        public static final int black=0x7f02001f;
        public static final int calendar=0x7f02000c;
        public static final int camera=0x7f02000d;
        public static final int clock=0x7f02000e;
        public static final int close=0x7f02000f;
        public static final int darkgray=0x7f02001d;
        public static final int default_bg=0x7f020010;
        public static final int ic_repeat_dark=0x7f020011;
        public static final int icon=0x7f020012;
        public static final int icon2=0x7f020013;
        public static final int icon2_down=0x7f020014;
        public static final int icon3=0x7f020015;
        public static final int icon3_down=0x7f020016;
        public static final int leftbutton=0x7f020017;
        public static final int music=0x7f020018;
        public static final int open=0x7f020019;
        public static final int openbg=0x7f02001a;
        public static final int rightbutton=0x7f02001b;
        public static final int tv=0x7f02001c;
        public static final int white=0x7f02001e;
    }
    public static final class id {
        public static final int but=0x7f090020;
        public static final int button1=0x7f090002;
        public static final int buttoncal=0x7f09002b;
        public static final int buttonok=0x7f09002a;
        public static final int datePicker1=0x7f090029;
        public static final int drawer1=0x7f090019;
        public static final int icon=0x7f090004;
        public static final int imageButton_left=0x7f090009;
        public static final int imageButton_right=0x7f09000b;
        public static final int imageView1=0x7f09000d;
        public static final int imageView2=0x7f09000c;
        public static final int imageView3=0x7f09000e;
        public static final int item1=0x7f09002e;
        public static final int item2=0x7f09002f;
        public static final int item3=0x7f090031;
        public static final int item4=0x7f090032;
        public static final int layout1=0x7f09001a;
        public static final int linearLayout1=0x7f09001e;
        public static final int logined=0x7f09002d;
        public static final int mainlayout=0x7f090006;
        public static final int myContent1=0x7f09001b;
        public static final int myImage1=0x7f09001c;
        public static final int tableLayout1=0x7f090007;
        public static final int tableLayout1_1=0x7f090028;
        public static final int tableLayout2=0x7f090008;
        public static final int termlayout=0x7f090027;
        public static final int text=0x7f090005;
        public static final int textView1=0x7f090000;
        public static final int textView1_2=0x7f09000f;
        public static final int textView2=0x7f090001;
        public static final int textView2_2=0x7f090010;
        public static final int textView3=0x7f090011;
        public static final int textView3_2=0x7f090012;
        public static final int textView4=0x7f090013;
        public static final int textView4_2=0x7f090014;
        public static final int textView5=0x7f090015;
        public static final int textView5_2=0x7f090016;
        public static final int textView6=0x7f090017;
        public static final int textView6_2=0x7f090018;
        public static final int textView_runtime=0x7f09002c;
        public static final int textterm=0x7f090003;
        public static final int textviewday=0x7f09000a;
        public static final int unlogin=0x7f090030;
        public static final int widgeView0=0x7f09001d;
        public static final int widgetText1=0x7f09001f;
        public static final int widgetText2=0x7f090021;
        public static final int widgetText3=0x7f090022;
        public static final int widgetText4=0x7f090023;
        public static final int widgetText5=0x7f090024;
        public static final int widgetText6=0x7f090025;
        public static final int widgetText7=0x7f090026;
    }
    public static final class layout {
        public static final int about=0x7f030000;
        public static final int grid=0x7f030001;
        public static final int main=0x7f030002;
        public static final int schedule_appwidget=0x7f030003;
        public static final int term=0x7f030004;
    }
    public static final class menu {
        public static final int option_menu=0x7f080000;
    }
    public static final class string {
        public static final int about=0x7f060004;
        public static final int aboutcontent=0x7f060005;
        public static final int aboutweb=0x7f060006;
        public static final int app_name=0x7f060001;
        public static final int app_name_cn=0x7f060002;
        public static final int auto_update_frequency_default_value=0x7f06000d;
        public static final int auto_update_frequency_key=0x7f06000c;
        public static final int auto_update_frequency_summary=0x7f06000e;
        public static final int auto_update_frequency_title=0x7f06000b;
        public static final int bg_default_value=0x7f060020;
        public static final int bg_key=0x7f06001f;
        public static final int bg_title=0x7f06001e;
        public static final int cancel=0x7f060012;
        public static final int class_address=0x7f060017;
        public static final int class_name=0x7f060016;
        public static final int class_no_default_value=0x7f060011;
        public static final int class_no_key=0x7f060010;
        public static final int class_no_title=0x7f06000f;
        public static final int classdetail_key=0x7f060014;
        public static final int classdetail_title=0x7f060013;
        public static final int editclass=0x7f060008;
        public static final int exit=0x7f060003;
        public static final int hello=0x7f060000;
        public static final int now=0x7f06000a;
        public static final int reload=0x7f060015;
        public static final int set=0x7f060021;
        public static final int startterm=0x7f060022;
        public static final int startterm_key=0x7f060024;
        public static final int startterm_set=0x7f060023;
        public static final int system_set=0x7f060009;
        public static final int view_1=0x7f060018;
        public static final int view_2=0x7f060019;
        public static final int view_3=0x7f06001a;
        public static final int view_4=0x7f06001b;
        public static final int view_5=0x7f06001c;
        public static final int view_6=0x7f06001d;
        public static final int yes=0x7f060007;
    }
    public static final class style {
        public static final int bg1=0x7f070002;
        public static final int bg2=0x7f070003;
        public static final int bg3=0x7f070004;
        public static final int bg4=0x7f070005;
        public static final int content=0x7f070000;
        public static final int no=0x7f070001;
    }
    public static final class xml {
        public static final int preferences=0x7f040000;
        public static final int schedulewidget=0x7f040001;
        public static final int systemset=0x7f040002;
        public static final int viewpreferences=0x7f040003;
    }
}
